"use client";

import { useEffect, useState } from "react";
import { AdminShell } from "../_shell";
import { api, getToken } from "@/lib/api";
import { fmtCurrency, fmtDate } from "@/lib/format";
import { Loading, Card, CardHeader, Badge, Empty } from "@/components/Card";
import { Modal, Field, inputCls, Btn } from "@/components/Modal";

/**
 * Phase 9 (revenue-engine program): AI Recommendation Center / human
 * approval. Every row here was generated by the deterministic Revenue
 * Engine (Phase 6, /api/cron/generate-pricing-recommendations) --
 * nothing on this page is a mock. Approving writes the rate into
 * villa_rates (with automatic history); rejecting just records the
 * decision. No autonomous execution -- every price change here required
 * a human click, per the mandate's explicit guardrail rule.
 *
 * Reuses the same pending_review -> reviewed_by/reviewed_at pattern
 * already proven by the CCTV disciplinary-reports module elsewhere in
 * this admin panel.
 *
 * Phase 8: the optional "AI Insight" button calls
 * /api/admin/pricing-insight, which asks Mkhsistem's AI Service to
 * phrase a plain-language explanation of the numbers already computed
 * above -- it never changes the recommendation and is fetched only on
 * click, not automatically for every row.
 */

interface Recommendation {
  id: string;
  room_type_id: string;
  target_date: string;
  current_rate: number;
  recommended_rate: number;
  delta_pct: number;
  reason_codes: string[];
  confidence: "low" | "medium" | "high";
  guardrail_status: string;
  occupancy_pct: number | null;
  pickup_bookings_3d: number | null;
  status: "pending_review" | "approved" | "rejected" | "executed" | "expired";
  generated_at: string;
  reviewed_by: string | null;
  reviewed_at: string | null;
  review_note: string | null;
  villa_room_types?: { code: string; name: string } | null;
}

const STATUS_TABS = [
  { key: "pending_review", label: "Menunggu Review" },
  { key: "executed", label: "Disetujui & Diterapkan" },
  { key: "rejected", label: "Ditolak" },
] as const;

const REASON_LABELS: Record<string, string> = {
  high_occupancy: "Okupansi tinggi",
  low_occupancy: "Okupansi rendah",
  recent_pickup: "Pickup baru-baru ini",
};

const CONFIDENCE_TONE: Record<string, "ok" | "pending" | "danger"> = { high: "ok", medium: "pending", low: "danger" };

export default function PricingRecommendationsPage() {
  const [status, setStatus] = useState<(typeof STATUS_TABS)[number]["key"]>("pending_review");
  const [rows, setRows] = useState<Recommendation[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [reviewTarget, setReviewTarget] = useState<{ rec: Recommendation; action: "approved" | "rejected" } | null>(null);
  const [note, setNote] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [insights, setInsights] = useState<Record<string, { loading: boolean; text?: string; error?: string }>>({});

  async function loadInsight(id: string) {
    setInsights((s) => ({ ...s, [id]: { loading: true } }));
    try {
      const token = getToken();
      const res = await fetch("/api/admin/pricing-insight", {
        method: "POST",
        headers: { "Content-Type": "application/json", ...(token ? { "x-villa-token": token } : {}) },
        body: JSON.stringify({ id }),
      });
      const body = await res.json().catch(() => null);
      if (!res.ok) throw new Error(body?.error || `HTTP ${res.status}`);
      setInsights((s) => ({ ...s, [id]: { loading: false, text: body.insight } }));
    } catch (e) {
      setInsights((s) => ({ ...s, [id]: { loading: false, error: e instanceof Error ? e.message : String(e) } }));
    }
  }

  function load() {
    setLoading(true);
    api
      .get<Recommendation[]>(`/admin/pricing-recommendations?status=${status}`)
      .then(setRows)
      .catch(() => setRows([]))
      .finally(() => setLoading(false));
  }

  useEffect(load, [status]);

  async function submitReview() {
    if (!reviewTarget) return;
    setSubmitting(true);
    try {
      await api.patch("/admin/pricing-recommendations", { id: reviewTarget.rec.id, status: reviewTarget.action, review_note: note || null });
      setReviewTarget(null);
      setNote("");
      load();
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <AdminShell pageTitle="Rekomendasi Harga" pageSub="Revenue Engine — semua rekomendasi butuh persetujuan admin">
      <div className="flex gap-2 mb-4">
        {STATUS_TABS.map((t) => (
          <button
            key={t.key}
            onClick={() => setStatus(t.key)}
            className={`text-[11px] font-semibold px-3 py-1.5 rounded-full border transition ${
              status === t.key ? "bg-ink text-base-900 border-ink" : "border-ink/15 text-ink/60 hover:border-ink/30"
            }`}
          >
            {t.label}
          </button>
        ))}
      </div>

      {loading && <Loading />}

      {!loading && rows && rows.length === 0 && (
        <Card>
          <Empty
            label={
              status === "pending_review"
                ? "Belum ada rekomendasi menunggu review. Revenue Engine jalan otomatis tiap hari — cek lagi nanti."
                : "Belum ada riwayat di kategori ini."
            }
          />
        </Card>
      )}

      {!loading && rows && rows.length > 0 && (
        <div className="space-y-3">
          {rows.map((r) => (
            <Card key={r.id}>
              <CardHeader
                title={`${r.villa_room_types?.name ?? "—"} · ${fmtDate(r.target_date, { day: "2-digit", month: "long", year: "numeric" })}`}
                subtitle={`Dibuat ${fmtDate(r.generated_at)}`}
                action={<Badge tone={CONFIDENCE_TONE[r.confidence]}>Confidence: {r.confidence}</Badge>}
              />
              <div className="p-4 sm:p-5">
                <div className="flex items-center gap-3 mb-3">
                  <div className="text-[13px] text-ink/40 line-through">{fmtCurrency(r.current_rate)}</div>
                  <div className="text-ink/30">→</div>
                  <div className="text-lg font-serif font-medium text-ink">{fmtCurrency(r.recommended_rate)}</div>
                  <Badge tone={r.delta_pct > 0 ? "ok" : "danger"}>
                    {r.delta_pct > 0 ? "+" : ""}
                    {Math.round(r.delta_pct * 1000) / 10}%
                  </Badge>
                </div>
                <div className="flex flex-wrap gap-1.5 mb-3">
                  {r.reason_codes.map((code) => (
                    <span key={code} className="text-[10px] px-2 py-0.5 rounded-full bg-ink/[0.06] text-ink/60">
                      {REASON_LABELS[code] ?? code}
                    </span>
                  ))}
                  {r.guardrail_status !== "within_range" && (
                    <span className="text-[10px] px-2 py-0.5 rounded-full bg-gold-500/15 text-gold-600">
                      Guardrail: {r.guardrail_status.replace("clamped_", "dibatasi ")}
                    </span>
                  )}
                </div>
                <div className="text-[10.5px] text-ink/40 mb-3">
                  Okupansi tanggal ini: {r.occupancy_pct ?? "—"}% · Booking baru (3 hari terakhir): {r.pickup_bookings_3d ?? 0}
                </div>

                {!insights[r.id] && (
                  <button
                    onClick={() => loadInsight(r.id)}
                    className="text-[10.5px] font-semibold text-ink/50 hover:text-ink/80 underline decoration-dotted mb-3"
                  >
                    ✨ Tampilkan AI Insight (penjelasan, bukan keputusan)
                  </button>
                )}
                {insights[r.id]?.loading && <div className="text-[10.5px] text-ink/40 mb-3 italic">Meminta penjelasan AI…</div>}
                {insights[r.id]?.error && (
                  <div className="text-[10.5px] text-ruby-500 mb-3">AI Insight gagal: {insights[r.id].error}</div>
                )}
                {insights[r.id]?.text && (
                  <div className="text-[11px] text-ink/70 bg-ink/[0.03] rounded-lg p-2.5 mb-3 italic">
                    ✨ {insights[r.id].text}
                  </div>
                )}

                {r.status !== "pending_review" && (
                  <div className="text-[10.5px] text-ink/40 border-t border-ink/[0.06] pt-2.5">
                    {r.status === "executed" ? "Disetujui" : "Ditolak"} oleh {r.reviewed_by} · {fmtDate(r.reviewed_at)}
                    {r.review_note && <div className="mt-1 italic">"{r.review_note}"</div>}
                  </div>
                )}
                {r.status === "pending_review" && (
                  <div className="flex gap-2 pt-2">
                    <Btn variant="primary" onClick={() => setReviewTarget({ rec: r, action: "approved" })}>
                      ✓ Setujui &amp; Terapkan
                    </Btn>
                    <Btn onClick={() => setReviewTarget({ rec: r, action: "rejected" })}>✕ Tolak</Btn>
                  </div>
                )}
              </div>
            </Card>
          ))}
        </div>
      )}

      <Modal
        open={!!reviewTarget}
        title={reviewTarget?.action === "approved" ? "Setujui rekomendasi harga" : "Tolak rekomendasi harga"}
        onClose={() => setReviewTarget(null)}
        footer={
          <>
            <Btn onClick={() => setReviewTarget(null)}>Batal</Btn>
            <Btn variant="primary" onClick={submitReview}>
              {submitting ? "Memproses…" : "Konfirmasi"}
            </Btn>
          </>
        }
      >
        {reviewTarget && (
          <>
            <div className="text-[12px] text-ink/70 mb-4">
              {reviewTarget.rec.villa_room_types?.name} · {fmtDate(reviewTarget.rec.target_date)} —{" "}
              {reviewTarget.action === "approved" ? (
                <>
                  tarif akan dicatat sebagai <strong>{fmtCurrency(reviewTarget.rec.recommended_rate)}</strong> untuk tanggal ini di kalender
                  harga internal (belum otomatis mengubah harga booking langsung — lihat catatan di dokumentasi).
                </>
              ) : (
                "rekomendasi ini tidak akan diterapkan."
              )}
            </div>
            <Field label="Catatan (opsional)">
              <textarea className={inputCls} rows={2} value={note} onChange={(e) => setNote(e.target.value)} placeholder="mis. alasan tambahan…" />
            </Field>
          </>
        )}
      </Modal>
    </AdminShell>
  );
}
